"""Markdown-to-Confluence-storage conversion for wiki page creation.

This module is intentionally pure: no environment reads, no Atlassian API calls,
and no page-specific behavior. It supports only the first-version Markdown
subset documented in the Confluence wiki page design.
"""

from __future__ import annotations

import html
import re
from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class ConversionWarning:
    type: str
    message: str
    source_excerpt: str

    def to_dict(self) -> dict[str, str]:
        return {
            "type": self.type,
            "message": self.message,
            "source_excerpt": self.source_excerpt,
        }


@dataclass(frozen=True, slots=True)
class ConvertedStorageDocument:
    value: str
    warnings: list[ConversionWarning]


def markdown_to_storage(markdown_text: str) -> ConvertedStorageDocument:
    """Convert the supported Markdown subset into Confluence storage XHTML."""

    lines = markdown_text.splitlines()
    warnings: list[ConversionWarning] = []
    blocks: list[str] = []
    index = 0
    while index < len(lines):
        line = lines[index]
        stripped = line.strip()
        if not stripped:
            index += 1
            continue
        if stripped.startswith("```"):
            block, index = _parse_fenced_code(lines, index)
            blocks.append(block)
            continue
        if _is_pipe_table_start(lines, index):
            block, index = _parse_table(lines, index)
            blocks.append(block)
            continue
        if stripped.startswith("#"):
            level = _heading_level(stripped)
            if level is not None:
                text = stripped[level:].strip()
                blocks.append(f"<h{level}>{_inline_markup(text)}</h{level}>")
                index += 1
                continue
        if _is_bullet(stripped):
            block, index = _parse_list(lines, index, ordered=False, warnings=warnings)
            blocks.append(block)
            continue
        if _is_numbered(stripped):
            block, index = _parse_list(lines, index, ordered=True, warnings=warnings)
            blocks.append(block)
            continue
        block, index = _parse_paragraph(lines, index, warnings)
        blocks.append(block)

    if not blocks:
        blocks.append("<p></p>")
    if warnings:
        blocks.insert(0, _notification_block(warnings))
    return ConvertedStorageDocument(value="\n".join(blocks), warnings=warnings)


def ai_generated_notice() -> str:
    return (
        '<ac:structured-macro ac:name="panel">'
        '<ac:parameter ac:name="title">AI-generated content</ac:parameter>'
        '<ac:parameter ac:name="borderColor">#1D7AFC</ac:parameter>'
        '<ac:parameter ac:name="bgColor">#E9F2FF</ac:parameter>'
        "<ac:rich-text-body>"
        "<p><strong>This page was generated by the ubitricity AI assistant local tool.</strong></p>"
        "<p>Please review important details before relying on or sharing this content.</p>"
        "</ac:rich-text-body>"
        "</ac:structured-macro>"
    )


def with_ai_generated_notice(storage_value: str) -> str:
    return f"{ai_generated_notice()}\n{storage_value}"


def _parse_fenced_code(lines: list[str], start: int) -> tuple[str, int]:
    opening = lines[start].strip()
    language = opening[3:].strip()
    index = start + 1
    code_lines: list[str] = []
    while index < len(lines):
        if lines[index].strip().startswith("```"):
            index += 1
            break
        code_lines.append(lines[index])
        index += 1
    language_attr = f' data-language="{html.escape(language, quote=True)}"' if language else ""
    code = html.escape("\n".join(code_lines))
    return f"<pre><code{language_attr}>{code}</code></pre>", index


def _parse_table(lines: list[str], start: int) -> tuple[str, int]:
    rows: list[list[str]] = [_split_table_row(lines[start])]
    index = start + 2
    while index < len(lines) and "|" in lines[index].strip() and lines[index].strip():
        rows.append(_split_table_row(lines[index]))
        index += 1
    body_rows = []
    for row_index, row in enumerate(rows):
        tag = "th" if row_index == 0 else "td"
        cells = "".join(f"<{tag}>{_inline_markup(cell.strip())}</{tag}>" for cell in row)
        body_rows.append(f"<tr>{cells}</tr>")
    return f"<table><tbody>{''.join(body_rows)}</tbody></table>", index


def _parse_list(
    lines: list[str],
    start: int,
    *,
    ordered: bool,
    warnings: list[ConversionWarning],
) -> tuple[str, int]:
    tag = "ol" if ordered else "ul"
    items: list[str] = []
    index = start
    while index < len(lines):
        stripped = lines[index].strip()
        if ordered and not _is_numbered(stripped):
            break
        if not ordered and not _is_bullet(stripped):
            break
        text = re.sub(r"^\d+\.\s+", "", stripped) if ordered else stripped[2:].strip()
        items.append(f"<li><p>{_convert_inline_with_images(text, warnings)}</p></li>")
        index += 1
    return f"<{tag}>{''.join(items)}</{tag}>", index


def _parse_paragraph(
    lines: list[str],
    start: int,
    warnings: list[ConversionWarning],
) -> tuple[str, int]:
    parts: list[str] = []
    index = start
    while index < len(lines):
        stripped = lines[index].strip()
        if (
            not stripped
            or stripped.startswith("```")
            or _heading_level(stripped) is not None
            or _is_bullet(stripped)
            or _is_numbered(stripped)
            or _is_pipe_table_start(lines, index)
        ):
            break
        parts.append(stripped)
        index += 1
    text = " ".join(parts)
    return f"<p>{_convert_inline_with_images(text, warnings)}</p>", index


def _convert_inline_with_images(text: str, warnings: list[ConversionWarning]) -> str:
    result: list[str] = []
    last = 0
    pattern = re.compile(r"!\[([^\]]*)\]\(([^)]+)\)")
    for match in pattern.finditer(text):
        result.append(_inline_markup(text[last : match.start()]))
        alt = match.group(1)
        source = match.group(2)
        source_excerpt = match.group(0)
        warnings.append(
            ConversionWarning(
                type="unsupported_image",
                message="Images are not uploaded or embedded by this tool version.",
                source_excerpt=source_excerpt,
            )
        )
        result.append(
            "<strong>[Unsupported image]</strong> "
            f'alt="{html.escape(alt, quote=True)}", '
            f'source="{html.escape(source, quote=True)}". '
            "Images are not uploaded by this tool version."
        )
        last = match.end()
    result.append(_inline_markup(text[last:]))
    return "".join(result)


def _inline_markup(text: str) -> str:
    escaped = html.escape(text, quote=True)
    escaped = re.sub(r"`([^`]+)`", r"<code>\1</code>", escaped)
    escaped = re.sub(r"\*\*([^*]+)\*\*", r"<strong>\1</strong>", escaped)
    return escaped


def _notification_block(warnings: list[ConversionWarning]) -> str:
    items = "".join(
        "<li>"
        f"{html.escape(warning.message)} "
        f"Source: <code>{html.escape(warning.source_excerpt)}</code>"
        "</li>"
        for warning in warnings
    )
    return (
        '<ac:structured-macro ac:name="warning"><ac:rich-text-body>'
        "<p>This page was generated from Markdown. Some content could not be fully converted.</p>"
        f"<ul>{items}</ul>"
        "</ac:rich-text-body></ac:structured-macro>"
    )


def _heading_level(stripped: str) -> int | None:
    match = re.match(r"^(#{1,3})\s+", stripped)
    if not match:
        return None
    return len(match.group(1))


def _is_bullet(stripped: str) -> bool:
    return stripped.startswith("- ")


def _is_numbered(stripped: str) -> bool:
    return re.match(r"^\d+\.\s+", stripped) is not None


def _is_pipe_table_start(lines: list[str], index: int) -> bool:
    if index + 1 >= len(lines):
        return False
    header = lines[index].strip()
    separator = lines[index + 1].strip()
    return (
        "|" in header
        and re.match(r"^\|?\s*:?-{3,}:?\s*(\|\s*:?-{3,}:?\s*)+\|?$", separator) is not None
    )


def _split_table_row(row: str) -> list[str]:
    stripped = row.strip()
    if stripped.startswith("|"):
        stripped = stripped[1:]
    if stripped.endswith("|"):
        stripped = stripped[:-1]
    return stripped.split("|")
